# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running tests'
        required: false
        default: 'Manual test trigger'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: running integration test
      env:
        ZAI_API: ${{ secrets.ZAI_API }}
        GLM_MODEL: ${{ secrets.GLM_MODEL}}
        PINECONE_API: ${{ secrets.PINECONE_API}}
        PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME}}
        PINECONE_NAMESPACE: ${{ secrets.PINECONE_NAMESPACE}}
        LOGGER_FILE: ${{ secrets.LOGGER_FILE}}
        MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
        MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        HOST: ${{ secrets.HOST}}
        PORT: ${{ secrets.PORT}}
        ENVIRONMENT: ${{ secrets.ENVIRONMENT}}
      run: |
        #1. Start Gunicorn in the process and save process id
        cd $GITHUB_WORKSPACE/backend/app
        gunicorn -c ./config/gunicorn_config.py app:app &
        GUNICORN_PID=$!

        #2. wait a few seconds for server to finish booting
        sleep 6

        #3. run request-based endpoint tests
        cd $GITHUB_WORKSPACE/backend/tests
        python -m endpoint
        TEST_EXIT_CODE=$?

        #4. Clean up: kill the background gunicorn process
        kill $GUNICORN_PID

        #5. Fail the CI step if the tests failed      
        exit $TEST_EXIT_CODE

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: production
    env:
      CONTAINER_NAME: ${{vars.CONTAINER_NAME}}           # set this to the name of the container in the
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: authenticate AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
        
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
        IMAGE_TAG: latest
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        aws ecr describe-repositories --repository-names $ECR_REPOSITORY || \
        aws ecr create-repository --repository-name $ECR_REPOSITORY --image-scanning-configuration scanOnPush=true
        
        cd $GITHUB_WORKSPACE/backend/app
        docker build -f Containerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
